import { prisma } from '../src/prisma';

const INITIAL_COURSES = [
  {
    id: "excel",
    title: "EXCEL",
    subtitle: "Esencial",
    color: "#ffffff",
    textColor: "#1d6b3a",
    iconType: "image",
    iconValue: "assets/CUERSO EXCEL.svg",
    category: "Cursos",
    modality: "A Distancia",
    level: "BÁSICO",
    duration: "40 horas (1 mes)",
    targetAudience: "Docentes y Personal Administrativo de SEIEM.",
    objective: "Adquirir habilidades prácticas para el manejo de datos, creación de reportes y automatización de tareas en Excel.",
    modules: JSON.stringify([
      "1. Introducción al entorno de Excel",
      "2. Fórmulas y funciones esenciales",
      "3. Tablas dinámicas y gráficos",
      "4. Automatización básica y macros"
    ]),
    illustrationUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    illustrationSide: "left",
    sede: "Plataforma Educativa Moodle",
  },
  {
    id: "gamificacion",
    title: "Gamificación",
    subtitle: "como metodología para los proyectos de aula",
    color: "#e8e4dd",
    textColor: "#56212f",
    iconType: "emoji",
    iconValue: "🧮",
    category: "Cursos",
    modality: "Mixta",
    level: "INTERMEDIO",
    duration: "60 horas (2 meses)",
    targetAudience: "Docentes de Educación Básica y Supervisores.",
    objective: "Desarrollar competencias para integrar herramientas digitales en la planificación y ejecución de clases.",
    modules: JSON.stringify([
      "1. Herramientas de Google Workspace",
      "2. Plataformas interactivas (Kahoot, Quizizz)",
      "3. Diseño de rúbricas digitales",
      "4. Proyecto integrador final"
    ]),
    illustrationUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    illustrationSide: "right",
    sede: "Aulas de Capacitación CoEEE",
  },
  {
    id: "scratch",
    title: "Diseño y Desarrollo",
    subtitle: "de animaciones educativas (Scratch)",
    color: "#e08a3a",
    textColor: "#56212f",
    iconType: "emoji",
    iconValue: "🐱",
    category: "Cursos",
    modality: "A Distancia",
  },
  {
    id: "mantenimiento",
    title: "Mantenimiento",
    subtitle: "Técnico a Equipos de Cómputo",
    color: "#9a9a9a",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "🔧",
    category: "Cursos",
    modality: "Presencial",
  },
  {
    id: "office",
    title: "Microsoft Office 2016",
    subtitle: "como recurso educativo",
    color: "#c44a3a",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "O",
    category: "Cursos",
    modality: "A Distancia",
  },
  {
    id: "classroom",
    title: "Google Classroom",
    subtitle: "introducción y dominio",
    color: "#4a8fc4",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "📚",
    category: "Cursos",
    modality: "A Distancia",
  },
  {
    id: "powerpoint",
    title: "PowerPoint",
    subtitle: "presentaciones de alto impacto",
    color: "#d24726",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "P",
    category: "Cursos",
    modality: "A Distancia",
  },
  {
    id: "word",
    title: "Word",
    subtitle: "documentos profesionales",
    color: "#2b579a",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "W",
    category: "Cursos",
    modality: "A Distancia",
  },
  {
    id: "canva",
    title: "Canva",
    subtitle: "diseño gráfico educativo",
    color: "#00c4cc",
    textColor: "#ffffff",
    iconType: "image",
    iconValue: "assets/Canva.svg",
    category: "Cursos",
    modality: "A Distancia",
  },
  {
    id: "ia_presencial",
    title: "Introducción a la IA",
    subtitle: "en educación",
    color: "#1e3a5f",
    textColor: "#ffffff",
    iconType: "image",
    iconValue: "assets/logo ia.png",
    category: "Cursos",
    modality: "Presencial",
    targetAudience:
      "Docentes, Asesores Técnico Administrativos, Asesores Técnico Pedagógicos, Directivos y Supervisores de las áreas administrativas de la DEE.",
    sede: "Sala de Capacitación del Departamento de CoEEE.",
    duration: "5 sesiones de 3 horas c/u (15 Horas).",
    capacity: "35 participantes.",
    objective:
      "Desarrollar competencias digitales y pedagógicas para la integración ética y creativa de herramientas de inteligencia artificial (IA) como ChatGPT, NotebookLM, Gamma y Gemini en el diseño, gestión y evaluación de experiencias de aprendizaje innovadoras.",
    modules: JSON.stringify([
      '"Descubriendo el poder de la IA en el aula"',
      '"ChatGPT: el aliado invisible del docente"',
      '"NotebookLM: del texto al conocimiento"',
      '"Gamma: presentaciones inteligentes para mentes creativas"',
      '"Gemini: la nueva frontera de la IA educativa"',
    ]),
  },
  {
    id: "bibliotecas",
    title: "Bibliotecas Virtuales",
    subtitle: "Acceso y búsqueda eficiente",
    color: "#1e3a5f",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "📚",
    category: "Talleres",
    modality: "A Distancia",
  },
  {
    id: "memoria",
    title: "Juegos Interactivos",
    subtitle: "Didáctica y lógica en el aula",
    color: "#c44a3a",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "🧠",
    category: "Talleres",
    modality: "Presencial",
  },
  {
    id: "classroom_intro",
    title: "Google Classroom",
    subtitle: "Introducción y configuración",
    color: "#2d6a4f",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "💻",
    category: "Talleres",
    modality: "A Distancia",
  },
  {
    id: "preguntas",
    title: "Evaluación Activa",
    subtitle: "Preguntas y respuestas",
    color: "#e9c46a",
    textColor: "#56212f",
    iconType: "emoji",
    iconValue: "❓",
    category: "Talleres",
    modality: "A Distancia",
  },
  {
    id: "tic_preescolar",
    title: "TIC en Preescolar",
    subtitle: "Estimulación y juego digital",
    color: "#74c0fc",
    textColor: "#56212f",
    iconType: "emoji",
    iconValue: "🎓",
    category: "Talleres",
    modality: "Presencial",
  },
  {
    id: "ia_basica",
    title: "IA en Educación",
    subtitle: "Introducción para docentes",
    color: "#6a4c93",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "🤖",
    category: "Talleres",
    modality: "A Distancia",
  },
  {
    id: "videos",
    title: "Creación de Video",
    subtitle: "Material didáctico interactivo",
    color: "#ff595e",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "📹",
    category: "Talleres",
    modality: "A Distancia",
  },
  {
    id: "rubricas",
    title: "Rúbricas Digitales",
    subtitle: "Evaluación del aprendizaje",
    color: "#8ac926",
    textColor: "#56212f",
    iconType: "emoji",
    iconValue: "📊",
    category: "Talleres",
    modality: "A Distancia",
  },
  {
    id: "docencia_digital",
    title: "Docencia Digital",
    subtitle: "Innovación educativa y TICs",
    color: "#1d3557",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "🏫",
    category: "Diplomados",
    modality: "A Distancia",
  },
  {
    id: "gestion_directiva",
    title: "Gestión Directiva",
    subtitle: "Liderazgo escolar y administración",
    color: "#457b9d",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "💼",
    category: "Diplomados",
    modality: "A Distancia",
  },
  {
    id: "uso_tic_preescolar",
    title: "TIC en Preescolar",
    subtitle: "Uso educativo de las tecnologías",
    color: "#e63946",
    textColor: "#ffffff",
    iconType: "image",
    iconValue: "assets/tic.png",
    category: "Diplomados",
    modality: "Presencial",
    targetAudience:
      "Docentes, Técnicos Docentes, Directivos, Supervisores, Responsables de Aulas de Medios y Asesores Técnico Pedagógicos de Educación Elemental de SEIEM.",
    sede: "Sala de Capacitación del Departamento de CoEEE, Boulevard Toluca - Metepec No 505, Col. La Purisima, Metepec, México.",
    duration: "150 horas",
    objective:
      "Que los participantes de nivel preescolar, al término del diplomado, adquieran los conocimientos y desarrollen las habilidades básicas del uso de la computadora para incorporar las TIC en sus aulas como medio de aprendizaje.",
    modules: JSON.stringify([
      "I. Uso e incorporación de las TIC en educación preescolar",
      "II. Introducción a la computadora",
      "III. Uso de Office",
      "IV. Uso y aplicación de software educativo",
      "V. Portales Educativos",
    ]),
  },
  {
    id: "diseno_curricular",
    title: "Diseño Curricular",
    subtitle: "Planificación contemporánea",
    color: "#e63946",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "📝",
    category: "Diplomados",
    modality: "Presencial",
  },
  {
    id: "entornos_virtuales",
    title: "Entornos Virtuales",
    subtitle: "Diseño de aulas en línea",
    color: "#a8dadc",
    textColor: "#56212f",
    iconType: "emoji",
    iconValue: "🌐",
    category: "Diplomados",
    modality: "A Distancia",
  },
  {
    id: "metodologias_activas",
    title: "Metodologías Activas",
    subtitle: "ABP, STEM y aula invertida",
    color: "#f1faee",
    textColor: "#56212f",
    iconType: "emoji",
    iconValue: "👥",
    category: "Diplomados",
    modality: "Presencial",
  },
  {
    id: "inclusion_equidad",
    title: "Inclusión y Equidad",
    subtitle: "Atención a la diversidad en aula",
    color: "#f4a261",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "🤝",
    category: "Diplomados",
    modality: "A Distancia",
  },
  {
    id: "calidad_educativa",
    title: "Calidad Educativa",
    subtitle: "Evaluación y acreditación escolar",
    color: "#2a9d8f",
    textColor: "#ffffff",
    iconType: "emoji",
    iconValue: "🏆",
    category: "Diplomados",
    modality: "Presencial",
  },
];

async function main() {
  console.log("Starting seed...");
  
  // Create an admin user if not exists
  const admin = await prisma.user.upsert({
    where: { username: 'admin' },
    update: { passwordHash: require('bcrypt').hashSync('admin123', 10) },
    create: {
      username: 'admin',
      name: 'Administrator',
      passwordHash: require('bcrypt').hashSync('admin123', 10),
      role: 'ADMIN'
    }
  });

  for (const course of INITIAL_COURSES) {
    await prisma.course.upsert({
      where: { id: course.id },
      update: {},
      create: course,
    });
  }

  console.log("Seed completed.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
